[package]
name = "resume"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.46.1", features = ["full"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"]}
serde_yaml = "0.9"
