[package]
name = "autocv-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace= true, features = ["full"] }
futures = {workspace= true}
anyhow = {workspace= true}
autocv-core = { path = "../autocv-core" }
